### ISSUE TITLE
[LOGIN] EOS login gets stuck in a loop

### ISSUE THREAD

**Issue by AlphaDoe** [YoYoGames/GMEXT-EpicOnlineServices#4] opened 2023-06-20 02:16 UTC
Hello,

I am a Gamemaker developer, and I am writing to address an issue I encountered while attempting to integrate achievements for my game application on the Epic Games platform.

I downloaded the EpicOnlineServices extension from the Yoyogames marketplace (https://marketplace.yoyogames.com/assets/11394/epiconlineservices-ext)
to facilitate the integration of Epic achievements. However, I encountered some difficulties when filling out the Extension Options required fields after I entered the SDK path.

Product ID.
Sandbox ID.
Deployment ID.
Client Credentials ID.
Client Credentials Secret
Encryption Key
Product Name etc.

Specifically, I am unsure about the encryption key field. Could you please provide guidance on where I can obtain the necessary information to complete this field? Additionally, I would appreciate clarification on whether I can leave it blank if no specific information is required because my game does not utilize encryption.

Furthermore, I am uncertain whether the Client Credentials ID and Client Credentials Secrets should be filled with the details associated with the "BPT Client" or if I should enter the Client ID and Secret found in my Product Settings on the Epic Games Developer Portal.

I have not come across any evidence that my game is successfully connected to Epic Games achievements. Upon running the Epic Online Services demo for achievements, I observed that nothing is displayed on the screen apart from the Gamemaker background in the Room_EpicGames_Achievements room. Based on these observations, I have reason to believe that there might have been errors or omissions in the fields I mentioned in my previous communication.

Therefore, I kindly request any assistance in identifying and rectifying any mistakes that may have occurred during the entry of the aforementioned fields. I am eager to ensure that the necessary information is correctly provided to establish the connection between my game and Epic Games achievements.

Thank you for your prompt attention to this matter. I appreciate your ongoing support and guidance.

**Comment by DiasFranciscoA** [comment] 2023-06-20 20:11
Hello @AlphaDoe,

Thank you for reaching out to us regarding the issue you are facing with our extension. In order to assist you further, we kindly request some additional information:

1. Output Log: To investigate the problem thoroughly, please provide us with the output log of the running game. This log should contain valuable information about whether the services were initialized properly or not. Sharing this log will greatly aid us in diagnosing the issue.

2. Runner and IDE Version: It is crucial for us to know the version of the runner and IDE you are using. Additionally, please specify whether you are using the Steam IDE or a different one. This information will help us narrow down the potential causes and provide you with more accurate guidance.

Furthermore, we would like to emphasize the importance of referring to the included documentation as well as the official documentation of Epic Online Services. While our extension aims to simplify the implementation of Epic Online Services, it relies on Epic's own documentation, which may undergo changes. Therefore, we highly recommend users to thoroughly read the documentation to ensure everything is properly configured. The extension's option values are referenced in the following sections of the documentation:

* EOS Platform Options: [Documentation Link](https://dev.epicgames.com/docs/en-US/api-ref/structs/eos-platform-options)
* EOS Platform Client Credentials: [Documentation Link](https://dev.epicgames.com/docs/en-US/api-ref/structs/eos-platform-client-credentials)

As you can verify, the values for ClientId, ClientSecret, and EncryptionKey are not necessary and should be left blank if not used.

We appreciate your understanding and cooperation in providing the requested information. Our team is committed to resolving this issue and ensuring a smooth experience with our extension.

If you have any further questions or concerns, please don't hesitate to let us know. We are here to help!

Best regards,

Francisco Dias

**Comment by AlphaDoe** [comment] 2023-06-21 03:09
To provide you with the necessary information, I have attached the output log for your reference. Please find the details below:

IDE Version: 2023.4.0.84
Current Runtime: 2023.4.0.113
Gamemaker IDE in use

Based on the Epic document, I have carefully reviewed the instructions but have encountered difficulty in resolving the issue. Specifically, I have left the fields for ClientId, ClientSecret, and EncryptionKey blank as instructed, but unfortunately, this approach has not yielded any positive results.

Given the circumstances, I kindly request your expertise and guidance in troubleshooting this matter. I would greatly appreciate any insights or instructions you can provide to help me resolve this integration issue.

**Comment by DiasFranciscoA** [comment] 2023-06-21 09:35
After looking at the log information you sent us. We can verify that everything seems to be working properly and the connection to the EOS services are working properly.

![image](https://github.com/YoYoGames/GMEXT-EpicOnlineServices/assets/85873067/ed86bcc5-4e25-4f9a-8608-b0ed3372ebf3)

We appreciate your efforts in providing the logs; however, we couldn't identify whether you were able to successfully log in to your Epic Account based on the provided logs. The logs primarily indicate that the app was launched and the window was subsequently closed. To better understand the issue, we kindly request more details regarding the login authentication process.

When utilizing achievements, please note that simply changing the starting room to the achievements room is not sufficient. The recommended approach is as follows:

1. Start with the default room in your game.
2. Proceed to log in to your Epic Account within the game.
3. After successfully logging in, utilize the provided buttons or navigation options to transition to the achievements room.

By following this process, you will be able to effectively access and interact with the achievements functionality.

We greatly appreciate your cooperation in providing more details on the login authentication process. This will assist us in diagnosing the issue more accurately and providing you with the necessary guidance.

**Comment by AlphaDoe** [comment] 2023-06-23 06:49
![Sample Login](https://github.com/YoYoGames/GMEXT-EpicOnlineServices/assets/137130125/89d36324-f770-4eec-a92e-5dfbf126ce1e)

Upon accessing the Obj_EpicGames_Menu sample and clicking "Log In," a popup requesting login credentials for the Epic account unexpectedly appeared, despite my account already being logged into both the Epic Games Launcher and the web platform. In an effort to troubleshoot this issue, I conducted a test by logging into my Epic Account. Subsequently, a "Connection Permission" popup emerged, offering the choices to "Allow" or "Cancel" the usage of my game in conjunction with my Epic Games Account (please refer to the attached JPG for visual reference).

![Permission popup](https://github.com/YoYoGames/GMEXT-EpicOnlineServices/assets/137130125/b78d36fd-fc58-4bd8-9ba6-535cf7f752e0)

After selecting "Allow," the permission box briefly disappeared, only to resurface approximately 15 seconds later. Despite numerous attempts to grant permission (exceeding 10 attempts), the permission box persistently reappeared. Whether opting to click "Allow" or "Cancel," the result was the same—an immediate return to the previous menu, still indicating the "LoginStatus" as "NotLoggedIn." Regrettably, neither option resolved the underlying issue, and as a consequence, the achievements remain inaccessible. For your convenience, I have also attached an output document for your reference.

I kindly request your guidance and advice in addressing this matter. Thank you.

**Comment by AlphaDoe** [comment] 2023-06-23 06:53
![Sample Login](https://github.com/YoYoGames/GMEXT-EpicOnlineServices/assets/137130125/8ff24014-7382-4f8b-b33d-ee5bc8228662)

Upon accessing the Obj_EpicGames_Menu sample and clicking "Log In," a popup requesting login credentials for the Epic account unexpectedly appeared, despite my account already being logged into both the Epic Games Launcher and the web platform. In an effort to troubleshoot this issue, I conducted a test by logging into my Epic Account. Subsequently, a "Connection Permission" popup emerged, offering the choices to "Allow" or "Cancel" the usage of my game in conjunction with my Epic Games Account (please refer to the attached JPG for visual reference).

After selecting "Allow," the permission box briefly disappeared, only to resurface approximately 15 seconds later. Despite numerous attempts to grant permission (exceeding 10 attempts), the permission box persistently reappeared. 
Regardless of whether the option selected was "Allow" or "Cancel," the outcome remained consistent, as the system continued to display the "LoginStatus" as "NotLoggedIn." In the case of choosing "Cancel," the user was redirected back to the previous menu. Regrettably, neither option resolved the underlying issue, and as a consequence, the achievements remain inaccessible. For your convenience, I have also attached an output document for your reference.

I kindly request your guidance and advice in addressing this matter. Thank you.

**Comment by DiasFranciscoA** [comment] 2023-06-23 08:33
The popup you encountered, requesting login credentials for the Epic account, is a normal and expected behavior even if you are already logged into the Epic Games Launcher or the web client. This popup is associated with the [EpicGames_Auth_Login](https://github.com/YoYoGames/GMEXT-EpicOnlineServices/wiki/Auth#EpicGames_Auth_Login) function and the specific options being used within it.

However, it appears that the login process is not functioning correctly on your end, as the "Connection Permission" popup continues to reappear despite multiple attempts to grant permission.

To address this matter effectively, we kindly request that you open a helpdesk ticket and submit your project files to us. This will allow our support team to analyze the issue in-depth and provide you with appropriate assistance. Once you have opened the ticket, please provide us with the ticket ID here, so we can easily locate and prioritize your case within our helpdesk database.

Thank you for your cooperation, and we appreciate your efforts in resolving this issue.

**Comment by AlphaDoe** [comment] 2023-06-23 10:47
Does it have anything to do with activating Epic Games Social Overlay? The Social Overlay is not present in the build when pressing SHIFT & F3.

**Comment by DiasFranciscoA** [comment] 2023-06-23 11:03
Hello again,

The overlay should be working as it doesn't require authentication to Epic Online Services to work.

To ensure the security and confidentiality of your project, we highly recommend that you create a HelpDesk ticket through our [contact page](https://accounts.yoyogames.com/contact-us). By submitting your project through the HelpDesk ticket system, we can guarantee the privacy of your information and provide a more secure and appropriate channel for discussing sensitive details.

In the HelpDesk ticket, we may require additional information to better understand and address the issue you are facing. Rest assured that any confidential or private information shared through the HelpDesk ticket system will be handled securely and only used for the purpose of assisting you with the specific issue.

Thank you for your understanding and cooperation. Please proceed to the HelpDesk ticket system to file your project, and once you have done so, kindly provide us with the ticket number here for reference.

Best regards,

Francisco Dias

**Comment by DiasFranciscoA** [comment] 2023-06-23 11:12
After looking at your "CONNECTION PERMISSION" image I can say that if you are using the demo you should be requesting additional permissions for your app. The permissions you should be asking for when using the demo are the following:

![image](https://github.com/YoYoGames/GMEXT-EpicOnlineServices/assets/85873067/f28e47d8-1c76-4c97-af1f-4f4059c1bfe8)

Looking at the Demo code you can see that the scopes that are being requested permissions for are the following:

<img width="553" alt="image" src="https://github.com/YoYoGames/GMEXT-EpicOnlineServices/assets/85873067/a4ff3af8-7555-4dd5-ad95-927854e7a172">

You should enable those in the EpicGames developer portar for you game in order to use the demo or achievements correctly.

**Comment by AlphaDoe** [comment] 2023-06-23 11:21
I added FriendsList and AS_Presence , same result. After numerous attempts to grant permission, the permission box persistently reappeared.
![Permission popup2](https://github.com/YoYoGames/GMEXT-EpicOnlineServices/assets/137130125/1a837c96-544a-4c57-9daf-e9ad57bd0690)

Can I confirm that Epic Games Social Overlay does not need the EpicOnlineServices Extension to work? For example, if I delete EpicOnlineServices extension on gamemaker, will Epic Games Social Overlay still work by default?

**Comment by DiasFranciscoA** [comment] 2023-06-23 11:27
The EpicOnlineServices extension is still required for the Epic Games Social Overlay to work in GameMaker. GameMaker does not have built-in functionality to interact with the Epic Online Services API without the extension. Therefore, deleting the EpicOnlineServices extension from GameMaker would prevent the Epic Games Social Overlay from functioning correctly.

If you have any further questions or concerns, please feel free to ask. We are here to assist you.

Best regards,

Francisco Dias

**Comment by AlphaDoe** [comment] 2023-06-23 11:33
Hence, I am puzzled why the Epic Team informed me that the Social Overlay is not present in the build when pressing SHIFT & F3. 

Is there anything wrong with the EpicOnlineServices extension? Do I need to code anything in gamemaker for the Social Overlay to work with the EpicOnlineServices extension?

**Comment by DiasFranciscoA** [comment] 2023-06-23 12:05
In order to provide further assistance, we kindly request that you create a HelpDesk ticket through our [contact page](https://accounts.yoyogames.com/contact-us) and submit your project via the ticketing system.

Within the HelpDesk ticket, we may need to gather additional information from you to gain a better understanding of the issue you are experiencing and effectively address it.

We appreciate your understanding and cooperation in using the HelpDesk ticket system for submitting your project. Once you have completed the submission, please provide us with the ticket number here for reference.

Thank you for your cooperation, and we look forward to assisting you through the HelpDesk ticketing system.

**Comment by AlphaDoe** [comment] 2023-06-23 14:04
I have some concern providing my game's Epic Platform Client Credentials ID and Client Credentials Secret due to confidentiality. Do you have those on your side for testing that you can key in yourself after I sent you my project.yyp file?

Then I will proceed to leave the Client Credentials ID and Client Credentials Secret fields blank. 
![Extension Fields](https://github.com/YoYoGames/GMEXT-EpicOnlineServices/assets/137130125/cd32fbca-1e58-4d30-89da-c8f989ce85f2)

**Comment by DiasFranciscoA** [comment] 2023-06-23 14:07
You shouldn't provide information here... you should use this link:

[contact page](https://accounts.yoyogames.com/contact-us)

to contact us directly through the helpdesk so it's a secure and private message.

**Comment by AlphaDoe** [comment] 2023-06-23 14:09
I know. I will use that link, but I am asking if can leave those fields blank even for that link .

I believe your team should have your own field data for testing too..

**Comment by DiasFranciscoA** [comment] 2023-06-23 14:26
Given that the extension is fully working for other users and in the demo project, it suggests that there may be specific configurations or setup-related factors affecting your implementation. In order to provide more tailored assistance, we may require access to your project data to analyze the specific setup and configurations in question.

We appreciate your understanding and cooperation in this matter. Our aim is to ensure your positive experience with the extension, and we will do our best to assist you within the limitations of the support options available.

Best regards,

Francisco Dias

**Comment by AlphaDoe** [comment] 2023-06-23 14:45
Done. The ticket number is: ([#210258])

However, via the helpdesk ticket system, I do not see any option button for me to upload my project. How do I send you the file?

**Comment by DiasFranciscoA** [comment] 2023-06-23 14:51
From the link above you would need to login, then select the following:
<img width="677" alt="image" src="https://github.com/YoYoGames/GMEXT-EpicOnlineServices/assets/85873067/f274cca4-8695-4ff0-bb02-635a4e5ce313">

Next scroll to the end of the page and select:
<img width="687" alt="image" src="https://github.com/YoYoGames/GMEXT-EpicOnlineServices/assets/85873067/441ea440-ff4f-4707-9eda-8d63c84571b5">

Then fill in all the required data and you should also be able to attach you project.

Since you've already created the ticket I would ask you if you are able to attach it to the ticket if you check the ticket afterwards from the link you received on the email?

**Comment by AlphaDoe** [comment] 2023-06-23 14:59
Yep, after clicking the link from the email, I am able to attached the file. I have sent it via the ticket link, please take a look, thanks.

**Comment by DiasFranciscoA** [comment] 2023-06-27 21:16
I'll be closing this issue. Is was properly addressed through the helpdesk. 

For future reference the problem was related with extra features being enabled in the dev portal. Anti-Cheat module is not supported by the extension and turning it on will result in authentication problems.

**Closed as completed** 2023-06-27 21:17 UTC
Labels: EpicOnline, extension
